### ISSUE TITLE
plot_dist and plot_ts not working with covariates?

### ISSUE THREAD

**Issue by RonEfrat** [TheoMichelot/hmmTMB#19]
Thanks for the great package1

After adding a covariate or a random factor to the observation, plot_dist and plot_ts produce an error:

> Error in sub_obs_probs[1, ] : incorrect number of dimensions

Here is my code:
```
f_Obs = list(Beeline = list(mean = ~ Mean.Wind.speed)) ## I get the same result for different covariates or for random factor, e.g. list(mean = ~ s(Tag, bs = "re"))

hid1 = MarkovChain$new(data = Daily.ForHMM, n_states = 2, 
                       initial_state = "shared")
dists = list(Beeline = "gamma2", Az.Change.Rad = "vm")
par0 = list(Beeline = list(mean = c(10, 80), sd = c(1, 75)),
            Az.Change.Rad = list(mu = c(0, 0), kappa = c(1, 10)))

obs1 = Observation$new(data = Daily.ForHMM, dists = dists,
                       par = par0, n_states = 2, formulas = f_Obs)

hmm1 <- HMM$new(obs = obs1, hid = hid1)
hmm1$fit(silent = TRUE)

hmm1$plot_dist("Beeline")
hmm1$plot_dist("Az.Change.Rad")
hmm1$plot_ts("Long.S", "Lat.S") +
  geom_point(size = 0.5) +
  coord_equal()
```

*I apologize if I missed an explanation for this anywhere
Thank you

**Comment by TheoMichelot** [comment]
I can't reproduce the error so it's hard to tell what the problem is. Can you please try to run the code below and let me know whether you get the same error? You will need to install the package moveHMM, which loads the `haggis_data` data set I'm using.

``` R
library(hmmTMB)
library(moveHMM)
haggis <- prepData(haggis_data, type = "UTM")

hid <- MarkovChain$new(data = haggis, n_states = 2, 
                       initial_state = "shared")

dists <- list(step = "gamma2")
par0 <- list(step = list(mean = c(1, 5), sd = c(1, 5)))
f <- list(step = list(mean = ~temp))
obs <- Observation$new(data = haggis, n_states = 2,
                       dists = dists, par = par0,
                       formulas = f)

hmm <- HMM$new(obs = obs, hid = hid)
hmm$fit(silent = TRUE)

hmm$plot_dist("step")
hmm$plot_ts("step")
```

**Comment by RonEfrat** [comment]
OK, I found the problem and it was with my data. Sorry for that.
One of my ID's only had one day, so no change in angle. Would have been nice if there was a warning or error when running the model, before trying to plot.

Sorry again for the trouble.

**Comment by TheoMichelot** [comment]
Okay, good to hear you figured this out -- good luck with the analysis!
